# Copyright 2021 Nordcloud Oy or its affiliates. All Rights Reserved.

name: Auto update go dependencies
on:
  schedule:
    # runs at 2:00 am on 1 and 15 day of month
    - cron: '0 2 1,15 * *'
  workflow_dispatch:

jobs:
  dependencies-autoupdate:
    name: Dependencies update
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      GOPROXY: "direct"
      GOSUMDB: "off"

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          node-version: '16'
        id: nodejs

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run auto dependency update for ./
        uses: nordcloud/dependencies-autoupdate@nordcloud-v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          priv-token: ${{ secrets.GHTOKEN }}
          update-path: ./


